theme: jekyll-theme-slate
title: Лакин Никита
description: Senior Python Developer / Team Lead с 5-летним опытом\nСпециализация: высоконагруженные backend-системы, микросервисная архитектура, платежные решения и тимлидство
github:
    is_project_page: false
markdown: kramdown
